import 'package:firebase_core/firebase_core.dart';

/// Initializes Firebase without making the rest of the app depend on project
/// credentials. Native builds use google-services files generated by
/// `flutterfire configure`; web builds can provide the standard FIREBASE_*
/// dart-defines until firebase_options.dart is generated.
abstract final class FirebaseBootstrap {
  static String? lastError;

  static bool get isReady => Firebase.apps.isNotEmpty;

  static Future<bool> initialize() async {
    if (isReady) return true;
    try {
      const apiKey = String.fromEnvironment('FIREBASE_API_KEY');
      if (apiKey.isNotEmpty) {
        await Firebase.initializeApp(
          options: const FirebaseOptions(
            apiKey: apiKey,
            appId: String.fromEnvironment('FIREBASE_APP_ID'),
            messagingSenderId:
                String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID'),
            projectId: String.fromEnvironment('FIREBASE_PROJECT_ID'),
            databaseURL: String.fromEnvironment('FIREBASE_DATABASE_URL'),
            authDomain: String.fromEnvironment('FIREBASE_AUTH_DOMAIN'),
            storageBucket: String.fromEnvironment('FIREBASE_STORAGE_BUCKET'),
          ),
        );
      } else {
        await Firebase.initializeApp();
      }
      lastError = null;
      return true;
    } catch (error) {
      lastError = error.toString();
      return false;
    }
  }
}
