// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXdecG1yp923NQtFG0I982n55cGDKzX7c',
    appId: '1:1009997802044:web:19005ca40c3b553520b139',
    messagingSenderId: '1009997802044',
    projectId: 'pickleball-simulator',
    authDomain: 'pickleball-simulator.firebaseapp.com',
    databaseURL:
        'https://pickleball-simulator-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pickleball-simulator.firebasestorage.app',
    measurementId: 'G-57EP1LQYB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI-wOWu3YuCa1BSUri3dp-etFdQy6nLZ0',
    appId: '1:1009997802044:android:0579cab974652a3820b139',
    messagingSenderId: '1009997802044',
    projectId: 'pickleball-simulator',
    databaseURL:
        'https://pickleball-simulator-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pickleball-simulator.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTZzvJKfVuJspRkRvTC6wmkFkfxfFJD_U',
    appId: '1:1009997802044:ios:49da4d4b392b04f420b139',
    messagingSenderId: '1009997802044',
    projectId: 'pickleball-simulator',
    databaseURL:
        'https://pickleball-simulator-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pickleball-simulator.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
}
